---
title: "Using Spatial R Packages with GSODR"
author: "Adam H Sparks"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Using Spatial R Packages}
  %\VignetteEncoding{UTF-8}
---



# Creating Spatial Files

Because the stations provide geospatial location information, it is possible to
create a spatial file. [GeoPackage files](http://www.geopackage.org) are a open,
standards-based, platform-independent, portable, self-describing compact
format for transferring geospatial information, which handle vector files much
like shapefiles do, but eliminate many of the issues that shapefiles have with
field names and the number of files.

Converting the GSOD data to a spatial object is rather simple. In R there are
two options, _sp_ and _sf_. The _sp_ format is older and more well established,
but _sf_ offers some new exciting possibilities.

## Convert to an _sp_ SpatialPointsDataFrame

For this example we convert the data to a _sp_ object. You might use this one
to save GeoPackage or ESRI shapefiles for sharing or analysis in another GIS
program.


```r
# get GSOD data
library(GSODR)
library(sp)
GSOD <- get_GSOD(years = 2015, country = "Australia")

# convert to SpatialPointsDataFrame
GSOD_sp <- GSOD
coordinates(GSOD_sp) <- ~ LONGITUDE + LATITUDE
proj4string(GSOD_sp) <- CRS("+proj=longlat +datum=WGS84")
```

## Saving _sp_ objects

Using `writeOGR()` it is simple to save as a GeoPackage file.


```r
library(rgdal)
```

```
## rgdal: version: 1.4-4, (SVN revision 833)
##  Geospatial Data Abstraction Library extensions to R successfully loaded
##  Loaded GDAL runtime: GDAL 2.1.3, released 2017/20/01
##  Path to GDAL shared files: /Users/adamsparks/Library/R/3.x/library/sf/gdal
##  GDAL binary built with GEOS: FALSE 
##  Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
##  Path to PROJ.4 shared files: /Users/adamsparks/Library/R/3.x/library/sf/proj
##  Linking to sp version: 1.3-1
```

```r
writeOGR(GSOD_sp,
         dsn = path.expand("~/"),
         layer = "GSOD",
         driver = "GPKG")
```

```
## Error in writeOGR(GSOD_sp, dsn = path.expand("~/"), layer = "GSOD", driver = "GPKG"): Creation of output file failed
```

Using `writeOGR()` it is simple to save as an ESRI shapefile.


```r
library(rgdal)
writeOGR(GSOD_sp,
         dsn = path.expand("~/"),
         layer = "GSOD",
         driver = "ESRI Shapefile")
```

```
## Error in writeOGR(GSOD_sp, dsn = path.expand("~/"), layer = "GSOD", driver = "ESRI Shapefile"): layer exists, use a new layer name
```

## Converting to an _sf_ object

Simple features are an ISO defined standard that now have support in R. From the
[_sf_ vignette](https://r-spatial.github.io/sf/articles/sf1.html):

> Simple features or simple feature access refers to a formal standard (ISO
19125-1:2004) that describes how objects in the real world can be represented in
computers, with emphasis on the spatial geometry of these objects. It also
describes how such objects can be stored in and retrieved from databases, and
which geometrical operations should be defined for them.
The standard is widely implemented in spatial databases (such as PostGIS),
commercial GIS (e.g., ESRI ArcGIS) and forms the vector data basis for libraries
such as GDAL. A subset of simple features forms the GeoJSON standard.

For this example, we convert the GSOD data to an _sf_ object.


```r
library(sf)
```

```
## Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3
```

```r
GSOD_SF <- st_as_sf(x = GSOD,
                    coords = c("LONGITUDE", "LATITUDE"),
                    crs = "+proj=longlat +datum=WGS84")

str(GSOD_SF)
```

```
## Classes 'sf', 'data.table' and 'data.frame':	174954 obs. of  43 variables:
##  $ STNID           : chr  "941000-99999" "941000-99999" "941000-99999" "941000-99999" ...
##  $ NAME            : chr  "KALUMBURU" "KALUMBURU" "KALUMBURU" "KALUMBURU" ...
##  $ CTRY            : chr  "AS" "AS" "AS" "AS" ...
##  $ STATE           : chr  "" "" "" "" ...
##  $ ELEVATION       : num  24 24 24 24 24 24 24 24 24 24 ...
##  $ BEGIN           : int  20010912 20010912 20010912 20010912 20010912 20010912 20010912 20010912 20010912 20010912 ...
##  $ END             : int  20190810 20190810 20190810 20190810 20190810 20190810 20190810 20190810 20190810 20190810 ...
##  $ YEARMODA        : Date, format: "2015-01-01" "2015-01-02" ...
##  $ YEAR            : int  2015 2015 2015 2015 2015 2015 2015 2015 2015 2015 ...
##  $ MONTH           : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ DAY             : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ YDAY            : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ TEMP            : num  26.9 27.2 26.3 27.3 27.3 26.7 28.1 28.7 27.6 27.8 ...
##  $ TEMP_ATTRIBUTES : chr  "16" "16" "16" "16" ...
##  $ DEWP            : num  23.2 23.3 23.8 24.1 24.3 24 23.6 23.3 21.9 22.3 ...
##  $ DEWP_ATTRIBUTES : chr  "16" "16" "16" "16" ...
##  $ SLP             : num  1004 1003 1003 1002 1001 ...
##  $ SLP_ATTRIBUTES  : chr  "16" "16" "16" "16" ...
##  $ STP             : num  1.6 0.5 NA 999 998.5 ...
##  $ STP_ATTRIBUTES  : chr  "16" "16" "16" "16" ...
##  $ VISIB           : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ VISIB_ATTRIBUTES: chr  " 0" " 0" " 0" " 0" ...
##  $ WDSP            : num  1.7 2.2 1.7 2 2.6 3.4 4.5 5.9 4.4 2.4 ...
##  $ WDSP_ATTRIBUTES : chr  "16" "16" "16" "16" ...
##  $ MXSPD           : num  4.1 4.1 4.1 4.1 5.7 5.7 6.7 9.3 7.7 4.6 ...
##  $ GUST            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ MAX             : num  31.5 31.3 29.2 32.1 31.4 28.6 30.2 31 32.7 32.9 ...
##  $ MAX_ATTRIBUTES  : chr  NA NA NA NA ...
##  $ MIN             : num  25 24.9 24.4 24.3 24.6 25.1 24.5 26.3 22.8 22.6 ...
##  $ MIN_ATTRIBUTES  : chr  NA "*" "*" NA ...
##  $ PRCP            : num  16.5 12.4 5.1 20.3 41.1 20.1 82.3 2.3 6.1 27.4 ...
##  $ PRCP_ATTRIBUTES : chr  "G" "G" "G" "G" ...
##  $ SNDP            : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ I_FOG           : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ I_RAIN_DRIZZLE  : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ I_SNOW_ICE      : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ I_HAIL          : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ I_THUNDER       : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ I_TORNADO_FUNNEL: int  NA NA NA NA NA NA NA NA NA NA ...
##  $ EA              : num  2.8 2.9 2.9 3 3 3 2.9 2.9 2.6 2.7 ...
##  $ ES              : num  3.5 3.6 3.4 3.6 3.6 3.5 3.8 3.9 3.7 3.7 ...
##  $ RH              : num  80 80.6 85.3 83.3 83.3 85.7 76.3 74.4 70.3 73 ...
##  $ geometry        :sfc_POINT of length 174954; first list element:  'XY' num  126.6 -14.3
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
##   ..- attr(*, "names")= chr  "STNID" "NAME" "CTRY" "STATE" ...
```

## Saving _sf_ objects

Writing a shapefile is a simple matter.


```r
write_sf(GSOD_SF, "GSOD.shp") # silently overwrites
```

As is writing a GeoPackage from the _sf_ object.


```r
write_sf(GSOD_SF, "~/GSOD.gpkg") # silently overwrites
```

After getting weather stations for Australia and creating a GeoPackage file,
_rgdal_ can import the data into R again in a spatial format.

Importing a GeoPackage file can be a bit tricky. The dsn will be the full path
along with the file name. The layer to be specified is "GSOD", this is specified
in the `get_GSOD()` function and will not change. The file name, specified in
the dsn will, but the layer name will not.


```r
library(rgdal)

AUS_stations <- readOGR(dsn = path.expand("~/GSOD.gpkg"), layer = "GSOD")
```

```
## Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv, : Cannot open data source
```

```r
class(AUS_stations)
```

```
## Error in eval(expr, envir, enclos): object 'AUS_stations' not found
```

Since GeoPackage files are formatted as SQLite databases you can use the
existing R tools for SQLite files
[(J. Stachelek 2016)](https://jsta.github.io/2016/07/14/geopackage-r.html). One
easy way is using _dplyr_. This option is much faster to load since it does not
load the geometry.


```r
library(dplyr)
```

```
## 
## Attaching package: 'dplyr'
```

```
## The following object is masked from 'package:gridExtra':
## 
##     combine
```

```
## The following objects are masked from 'package:data.table':
## 
##     between, first, last
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
AUS_sqlite <- tbl(src_sqlite(path.expand("~/GSOD.gpkg")), "GSOD")
```

```
## `path` must already exist, unless `create` = TRUE
```

```r
class(AUS_sqlite)
```

```
## Error in eval(expr, envir, enclos): object 'AUS_sqlite' not found
```

# References
Stachelek, J. (2016) Using the Geopackage Format with R.
URL: https://jsta.github.io/2016/07/14/geopackage-r.html
