
# Check that get_inventory functions properly ----------------------------------
context("get_inventory()")
test_that("get_inventory fetches the inventory doc and returns a data frame", {
  skip_on_cran()
  x <- get_inventory()
  expect_length(x, 14)
  expect_is(x, "data.frame")
  expect_is(x$STNID, "character")
  expect_is(x$YEAR, "integer")
  expect_is(x$JAN, "integer")
  expect_is(x$FEB, "integer")
  expect_is(x$MAR, "integer")
  expect_is(x$APR, "integer")
  expect_is(x$MAY, "integer")
  expect_is(x$JUN, "integer")
  expect_is(x$JUL, "integer")
  expect_is(x$AUG, "integer")
  expect_is(x$SEP, "integer")
  expect_is(x$OCT, "integer")
  expect_is(x$NOV, "integer")
  expect_is(x$DEC, "integer")
})
