# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "isd_history", # <get_GSOD>
  "isd_history", # <get_inventory>
  "STNID", # <get_inventory>
  "isd_history", # <nearest_stations>
  "distance_km", # <nearest_stations>
  "STNID", # <.process_csv>
  "STP", # <.process_csv>
  "YEARMODA", # <.process_csv>
  "DATE", # <.process_csv>
  "YEAR", # <.process_csv>
  "MONTH", # <.process_csv>
  "DAY", # <.process_csv>
  "YDAY", # <.process_csv>
  "TEMP", # <.process_csv>
  "DEWP", # <.process_csv>
  "WDSP", # <.process_csv>
  "MXSPD", # <.process_csv>
  "GUST", # <.process_csv>
  "VISIB", # <.process_csv>
  "MAX", # <.process_csv>
  "MIN", # <.process_csv>
  "PRCP", # <.process_csv>
  "SNDP", # <.process_csv>
  "EA", # <.process_csv>
  "ES", # <.process_csv>
  "RH", # <.process_csv>
  "I_FOG", # <.process_csv>
  "I_RAIN_DRIZZLE", # <.process_csv>
  "I_SNOW_ICE", # <.process_csv>
  "I_HAIL", # <.process_csv>
  "I_THUNDER", # <.process_csv>
  "I_TORNADO_FUNNEL", # <.process_csv>
  "FRSHTT", # <.process_csv>
  "isd_history", # <reformat_GSOD>
  "WBAN", # <update_internal_isd_history>
  "STNID", # <update_internal_isd_history>
  "USAF", # <update_internal_isd_history>
  "COUNTRY_NAME", # <update_internal_isd_history>
  NULL
))
